name: 'pwsh-module-build'
description: 'Builds a PowerShell Module using ModuleBuilder'
inputs:
  moduleName:
    description: 'Name of PowerShell Module to Test'
    required: true

runs:
  using: composite
  steps:
  - name: Download Build Output
    uses: actions/download-artifact@v2

  - uses: PoshCode/Actions/install-requiredmodules@v1

  - name: PowerShell
    shell: pwsh
    run: |
      Get-ChildItem -Path '${{ github.workspace }}/RequiredModules' -Recurse

  - uses: PoshCode/Actions/pester@v1
    with:
      codeCoveragePath: Modules/${{ inputs.moduleName }}
      moduleUnderTest: ${{ inputs.moduleName }}
      additionalModulePaths: '${{github.workspace}}/Modules; ${{github.workspace}}/RequiredModules'

  - name: Upload Results
    uses: actions/upload-artifact@v2
    with:
      name: Pester Results
      path: ${{github.workspace}}/*.xml
